apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-hello-world
  namespace: tutorial
spec:
  steps:
    - name: echo
      image: registry.cn-hangzhou.aliyuncs.com/knative-sample/alpine:3.9
      command:
        - sh
      args:
        - -c
        - |
          echo "Hello World!!"